openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:9045
    description: Generated server url
paths:
  /v0/clients:
    post:
      tags:
        - client-controller
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ClientDTO'
  /v0/clients/{id}:
    delete:
      tags:
        - client-controller
      operationId: deleteClient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    patch:
      tags:
        - client-controller
      operationId: updateClient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ClientDTO'
components:
  schemas:
    ClientDTO:
      type: object
      properties:
        name:
          type: string
        lastname:
          type: string
        email:
          type: string
        birthday:
          type: string
          format: date
        port:
          type: integer
          format: int32
        dni:
          type: string
