{
 "title": "License Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Estado de salud",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta promedio",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=~\".*\"}[5m])) by (job) \r\n/\r\nsum(rate(http_server_requests_seconds_count{job=~\".*\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio de fallas",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..|4..\", uri!=\"/actuator/prometheus\", job=~\".*\"}[1m])) by (job)\r\n/\r\nsum(rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", job=~\".*\"}[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cantidad de peticiones",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", job=~\".*\"}) by (job)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}