openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8088
    description: Generated server url
paths:
  /auth/register:
    post:
      tags:
        - security-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /auth/authenticate:
    post:
      tags:
        - security-controller
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    UserRegister:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lastname:
          type: string
        email:
          type: string
        username:
          type: string
        password:
          type: string
        roles:
          type: array
          items:
            type: string
    UserCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
