scrape_configs:

  - job_name: 'License Service Microservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:9050']
        labels:
          application: 'License Service Microservice Scrapping'
          
  - job_name: 'Client Query Service Microservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:9040']
        labels:
          application: 'Client Query Service Microservice Scrapping'

  - job_name: 'Client Command Service Microservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:9045']
        labels:
          application: 'Client Command Service Microservice Scrapping'
          
  - job_name: 'User Service Microservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:9030']
        labels:
          application: 'User Service Microservice Scrapping'

  - job_name: 'Authentication Service Microservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:8088']
        labels:
          application: 'Authentication Service Microservice Scrapping'