
services:
  mongo-service:
    image: mongo
    container_name: magic0-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: magic0
      MONGO_INITDB_ROOT_PASSWORD: mitocode
    volumes:
      - ./mongo-entry/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - 27017:27017
    networks:
      - magic0
    
    
  mongo-express:
    image: mongo-express
    container_name: magic0-mongo-express
    depends_on:
      - mongo-service
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: magic0
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://magic0:mitocode@mongo-service:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    networks:
      - magic0
     
  prometheus:
    image: prom/prometheus
    container_name: magic0-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
    - magic0     

  grafana:
    image: grafana/grafana-oss
    container_name: magic0-grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_DOMAIN: localhost
    networks:
    - magic0       
    
  loki:
    image: grafana/loki
    container_name: magic0-loki
    ports:
      - 3100:3100
    networks:
      - magic0
      
networks:
  magic0:
    name: magic0-network